accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

heestagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/edit/', views.edit, name='edit'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    author = models.CharField(max_length=100)
    body = models.TextField()
    created_at = models.DateTimeField()
    
    def __str__(self):
        return f'{self.author}: {self.body}'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.
def sign_up(request):
    context = {}
    
    # POST Method
    if request.method == 'POST':
        if (request.POST['username'] and
                request.POST['password'] and
                request.POST['password'] == request.POST['password_check']):
            
            new_user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password'],
            )
            
            auth.login(request, new_user)
            return redirect('posts:index')
            
        else:
            context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'
    
    # GET Method
    return render(request, 'accounts/sign_up.html', context)
    
def login(request):
    context = {}

    # POST Method
    if request.method == 'POST':
        if request.POST['username'] and request.POST['password']:

            user = auth.authenticate(
                request,
                username=request.POST['username'],
                password=request.POST['password']
            )

            if user is not None:
                auth.login(request, user)
                return redirect('posts:index')
            else:
                context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'

        else:
            context['error'] = '아이디와 비밀번호를 모두 입력해주세요.'

    # GET Method
    return render(request, 'accounts/login.html', context)
    
def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        
        
    return redirect('posts:index')
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.utils import timezone

# Create your views here.
def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'posts/index.html', context)
    
def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {
        'post': post
    }
    return render(request, 'posts/detail.html', context)
    
def new(request):
    return render(request, 'posts/new.html')    
    
def create(request):
    author = request.POST['author']
    body = request.POST['body']
    post = Post(author=author, body=body, created_at=timezone.now())
    post.save()
    
    return redirect('posts:detail', post_id=post.id)
    
def edit(request, post_id):
    post = Post.objects.get(id=post_id)
    context = { 'post': post }
    return render(request, 'posts/edit.html', context)
    
def update(request, post_id):
    post = Post.objects.get(id=post_id)
    post.author = request.POST['author']
    post.body = request.POST['body']
    post.save()
    
    return redirect('posts:detail', post_id=post.id)
    
def delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    
    return redirect('posts:index')    

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% if error %} 
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>    
    {% endif %}
    
    <form method="POST" action="{% url 'accounts:login' %}">
    	{% csrf_token %}
        <h1>Login</h1>
    
        <div class="form-group">
            <label for="username">아이디</label>
            <input type="text" id="username" name="username" placeholder="아이디">        
        </div>
        
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" id="password" name="password" placeholder="비밀번호">    
        </div>    
        
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% if error %} 
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>    
    {% endif %}
    
    <form method="POST" action="{% url 'accounts:sign_up' %}">
    	{% csrf_token %}
        <h1>Sign Up</h1>
    
        <div class="form-group">
            <label for="username">아이디</label>
            <input type="text" id="username" name="username" placeholder="아이디">        
        </div>
        
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" id="password" name="password" placeholder="비밀번호">    
        </div>    
    
        <div class="form-group">
            <label for="password_check">비밀번호</label>
            <input type="password" id="password_check" name="password_check" placeholder="비밀번호 확인">    	
        </div>
        
        <button type="submit" class="btn btn-primary">회원가입</button>
    </form>
</div>
{% endblock %}

posts/templates/posts/detail.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Heestagram</title>
        <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
    </head>
    <body>
        <h1>Post Detail</h1>
        
        {% if post %}
            <h2>작성자</h2>
            <p>{{ post.author }}</p>
            
            <h2>본문</h2>
            <p>{{ post.body }}</p>            
            
            <h2>게시일</h2>
            <p>{{ post.created_at }}</p>            
        {% else %}
            <p>No Post.</p>
        {% endif %}
        
        <a href="{% url 'posts:index' %}">목록</a>
        <a href="{% url 'posts:edit' post.id %}">수정하기</a>
        <a href="{% url 'posts:delete' post.id %}">삭제하기</a>
    </body>
</html>

posts/templates/posts/edit.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Heestagram</title>
        <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
    </head>
    <body>
        <h1>Edit Post</h1>
        
        <form action="{% url 'posts:update' post.id %}" method="POST">
            {% csrf_token %}
            
            <h2>작성자</h2>
            <input type="text" name="author" value="{{ post.author }}"/>
            
            <h2>본문</h2>
            <textarea cols=40 rows=10 name="body">{{ post.body }}</textarea>
            
            <br>
            <input type="submit" value="수정하기"/>
        </form>
        
        <a href="{% url 'posts:index' %}">목록</a>
    </body>
</html>

posts/templates/posts/index.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
{% endblock %} 

{% block content %}
    <div class="container">
        <h1>All Posts</h1>
        {% if posts %}
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>#</th>
                        <th>작성자</th>
                        <th>본문</th>
                        <th>게시일</th>
                        <th>상세</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                        <tr>
                            <th>{{ post.id }}</th>
                            <td>{{ post.author }}</td>
                            <td>{{ post.body }}</td>
                            <td>{{ post.created_at }}</td>
                            <td><a href="{% url 'posts:detail' post.id %}">보기</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            
        {% else %}
            <p>No Posts.</p>
        {% endif %}
        
        <a href="{% url 'posts:new' %}">글쓰기</a>        
    </div>
{% endblock %}

posts/templates/posts/new.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Heestagram</title>
        <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
    </head>
    <body>
        <h1>New Post</h1>
        
        <form action="{% url 'posts:create' %}" method="POST">
            {% csrf_token %}
            
            <h2>작성자</h2>
            <input type="text" name="author"/>
            
            <h2>본문</h2>
            <textarea cols=40 rows=10 name="body"></textarea>
            
            <br>
            <input type="submit" value="작성하기"/>
        </form>
        
        <a href="{% url 'posts:index' %}">목록</a>
    </body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Heestagram</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" />
        {% block style %}
        {% endblock %}        
    </head>
    <body>
        {% if user.is_authenticated %}
            <div class="container">
                <form action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    
                    {{ user.get_username }}님 환영합니다.
                    <button type="submit" class="btn btn-primary">LOGOUT</button>
                </form>
            </div>
        {% else %}
            <div class="container">
                <a href="{% url 'accounts:login' %}">
                    <button type="button" class="btn btn-primary">LOGIN</button>    
                </a>
                
                <a href="{% url 'accounts:sign_up' %}">
                    <button type="button" class="btn btn-primary">SIGN UP</button>    
                </a>                
            </div>        
        {% endif %}
        
        {% block content %}
        {% endblock %}
        
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>        
    </body>
</html>